version: '3'
services:
  myapp-main:
    image: golf-club-api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/flight_2024
      - spring.datasource.username=flight2024
      - spring.datasource.password=password

